script:
- "./update.sh"
env:
  global:
    - AWS_ACCESS_KEY=AKIAIBMZ3QYTBO2D25DQ
    - secure: "WiRkIw6Rg6m31pFMq4OhH2HdX7UX9Kobp2cVZALTzWpL/50e2Tsrw1aeedM/evyFlu0KJoZ1GcDlQlVXYHhDjAx3NQeCsUnqIsHXhwrDRjNfqwU/nicY+HEVCgQbPDxS4MIml+3K1zYKNyc/SOsJLVt/4h2YPYU9bF3+TMWQFZGkhIsE9awrPT89yN0KFTN8tkhU1oKXcS6s51dnv/6OUzB/+xChcISUCtsoKGcwLtrLmUHir4DYCStGeTugCYR9sHGMBhMRsDdyNUwmdAeeeJ37xKEW5Qb0Wy5PFTaUeRA612XFK2nLaxEbcqOZtaKPXsa3XnNu6Z6ym8E4EJbCNOg1Sx93yOA+ciAwOhS3oOO5BlXBeoseD8EGYNYA7aA+qz8ScsNjrwNhi3Rp+QoWpQeGEt+GewNSg9eyP32EH3p6xUrsvXnAWoKe4+Zj9nrhn79I71dHHuVrIJzR6zJQPw+FY095dIt2dDPsyc+2HsrLRqcQbhX5a+sg7O/ZLkk2bvft+ZkQtHkN0G7s+AtlVUm2U9XQrY0uxOTdIA5djwmvvD+xUxS5XOlkqQl+CHx/fLcGpVAAttAQwQTXf1ZuGSYCo+jfeZV5YQDDFCxczcHy95K0359dX6wzxPhIYDG08JbiAcs4dnrI7P6Au0WJx6XrC/0vmGDMO2OsUM/rnr8="
